version: "3.7"
services:
  web:
    image: nginx
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - swarm-net
    ports:
      - "8080:80"
networks:
  swarm-net:
    driver: overlay